# web.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  api.json: |
    {
      "ProductsApiUrl": "http://products-api.default.svc.cluster.local",
      "StockApiUrl": "http://stock-api.default.svc.cluster.local"
    }
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort  
  selector:
    app: web
  ports:
    - name: http
      port: 80
      targetPort: 80 
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: widgetario/web:21.03
          ports:
            - containerPort: 80
          env:
            - name: Widgetario__Theme
              value: "dark"
          volumeMounts:
            - name: web-config-volume
              mountPath: /app/secrets/api.json
              subPath: api.json
      volumes:
        - name: web-config-volume
          configMap:
            name: web-config
